import = [
	"~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"
opacity = 0.9
blur = true
startup_mode = "Maximized"

[font]

normal.family = "SauceCodePro Nerd Font Mono"
size =  18 

[scrolling]
history = 10000


